// Mocks generated by Mockito 5.1.0 from annotations
// in banku/test/unit_test/Novel_api_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:banku/model/api/novel_api.dart' as _i2;
import 'package:banku/model/novel_model.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [NovelAPI].
///
/// See the documentation for Mockito's code generation for more information.
class MockNovelAPI extends _i1.Mock implements _i2.NovelAPI {
  MockNovelAPI() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.NovelModel>> getPostNovel() => (super.noSuchMethod(
          Invocation.method(#getPostNovel, []),
          returnValue: Future<List<_i4.NovelModel>>.value(<_i4.NovelModel>[]))
      as _i3.Future<List<_i4.NovelModel>>);
  @override
  _i3.Future<List<_i4.NovelModel>> getMyPostNovel(dynamic user) =>
      (super.noSuchMethod(Invocation.method(#getMyPostNovel, [user]),
              returnValue:
                  Future<List<_i4.NovelModel>>.value(<_i4.NovelModel>[]))
          as _i3.Future<List<_i4.NovelModel>>);
}
